#!/bin/bash

checkExitCode() {
if [ $? -ne 0 ]; then
    echo "Error"
    exit 1;
fi
}

BASEDIR=`dirname $0`

. $BASEDIR/io.sh 1 0 1 "$@"

python $BASEDIR/Component3.py $INPUTS1 $OUTPUTS1

checkExitCode
